[hTTPServer]
host = "127.0.0.1"
port = "5080"
log_path = "\\logs\\server_log.json"

[logger]
level = "INFO"
path = "\\logs\\log.json"

[storage]
type = "memory"
database_url = "postgres://otus:otus@localhost:5432/calendar?sslmode=disable"

# TODO
# ...
